[package]
name = "exif-metadata-reader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kamadak-exif = "0.5.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
wasm-bindgen = "0.2"
wee_alloc = "0.4.5"
